### ISSUE TITLE
Image folder are not correct.

### ISSUE THREAD

**Issue by agillis** [gpambrozio/SquarelineToEsphome#10]
I run these commands

```
git clone https://github.com/gpambrozio/SquarelineToEsphome.git
git clone https://github.com/agillis/esphome-modular-lvgl-buttons.git
git clone https://github.com/agillis/esphome-hygrometer.git
uv run ./SquarelineToEsphome/squareline_to_esphome ./esphome-hygrometer/Squareline_files/hygrometer/hydro.spj -o ./squareline_generated.yaml 
cp esphome-hygrometer/SDL-SquarelineToEsphome-base.yaml .
esphome run SDL-SquarelineToEsphome-base.yaml

```

SquarelineToEsphome creates this section.

```
image:
- id: backround_png
  file: ./esphome-hygrometer/Squareline_files/hygrometer/./esphome-hygrometer/Squareline_files/hygrometer/assets/backround_RGB565.png
  type: RGB565
  transparency: alpha_channel
- id: dummy_image_png
  file: ./esphome-hygrometer/Squareline_files/hygrometer/./esphome-hygrometer/Squareline_files/hygrometer/assets/dummy_image_RGB565.png
  type: RGB565
  transparency: alpha_channel
```

There is an extra path in the directory names. Should just be this
```
 file: ./esphome-hygrometer/Squareline_files/hygrometer/assets/backround_RGB565.png
```

Looks like it doubling the folder name.
